# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.2.1"
    shell: /bin/bash --login -eo pipefail
    environment:
      SCRIPTS_LOCAL_FOLDER: "/Users/distiller/.scripts-iOS"
      SCRIPTS_REPO_PATH: "git@github.com:applicaster/Scripts-iOS.git"
      DEPLOY_VERSION: "0.6.2"
      DEPLOY_COMMAND: "/Users/distiller/.scripts-iOS/circleCi/openPluginForGitTag.sh"
    working_directory: /Users/distiller/Google-IMA-Client-TV/
    steps:
      - run:
          name: Ruby - set version
          command:  echo "ruby-2.4" > ~/.ruby-version

      - run:
          name: Ruby - version
          command:  ruby -v

      # Prepere Git and Submodules
      - restore_cache:
          keys:
            - Zapp-GoogleInteractiveAds-v1.1-{{ .Branch }}-{{ .Revision }}
            - Zapp-GoogleInteractiveAds-v1.1-{{ .Branch }}-
            - Zapp-GoogleInteractiveAds-v1.1-

      - checkout
      
      - run:
          name: Submodule update
          command: git submodule update --init --recursive

      - save_cache:
          name: Git - save cache
          key: Zapp-GoogleInteractiveAds-v1.1-{{ .Branch }}-{{ .Revision }}-{{ .Environment.version_id }}
          paths:
            - ".git"

      - run:
          name: Adding scripts
          command: |
            if [ ! -d "$SCRIPTS_LOCAL_FOLDER" ]; then
              git clone $SCRIPTS_REPO_PATH $SCRIPTS_LOCAL_FOLDER
            else
              echo "Repo exists in local path: $SCRIPTS_LOCAL_FOLDER"
              git -C $SCRIPTS_LOCAL_FOLDER fetch
              git -C $SCRIPTS_LOCAL_FOLDER fetch --tags
              git -C $SCRIPTS_LOCAL_FOLDER checkout
              git -C $SCRIPTS_LOCAL_FOLDER pull origin master
            fi
            git -C $SCRIPTS_LOCAL_FOLDER checkout $DEPLOY_VERSION

      # Prepare Bundler
      - restore_cache:
          name: Bundler - restore cache
          key: Zapp-GoogleInteractiveAds-v1.0-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundler - update dependencies
          command: bundle update

      - save_cache:
          name: Bundler - save cache
          key: Zapp-GoogleInteractiveAds-v1.0-{{ checksum "Gemfile.lock" }}
          paths:
            - /Users/distiller/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems

      # Restore Cocoapods cache, save cache on lower level, after pod update
      - restore_cache:
          name: CocoaPods - restore cache
          key: Zapp-Zapp-GoogleInteractiveAds-CocoaPods-v1.0

      - run:
          name: CocoaPods - version
          command: bundle exec pod --version

      # Pod install
      - run:
          name: CocoaPods - update dependencies
          command: bundle exec pod install --project-directory=./tvOS/GoogleInteractiveMediaAdsTvOS

      # Cache CocoaPods
      - save_cache:
          name: CocoaPods - save cache
          key: Zapp-Zapp-GoogleInteractiveAds-CocoaPods-v1.0
          paths:
            - "Pods"
            - "Podfile.lock"

      # Tests
      - run:
          name: Tests - start
          command: bundle exec fastlane tvos test

      # Deploy
      - deploy:
          name: Creating tag
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ] || [[ "$CIRCLE_BRANCH" == "hotfix_"* ]];
            then
              echo "Execute deploy script"
              $DEPLOY_COMMAND "/Users/distiller/Google-IMA-Client-TV/tvOS/GoogleInteractiveMediaAdsTvOS/GoogleInteractiveMediaAdsTvOS"
            else
              echo "Branch is not master, deploy process will be skipped"
            fi

      - store_test_results:
          path: ./CircleArtifacts/test-results

      - store_artifacts:
          path: ./CircleArtifacts

workflows:
  version: 2
  build:
    jobs:
      - build
